services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10s ; python ./script.py"
    environment:
      - FIND_IP_LOCATION=1.1.1.1
    depends_on:
      - mysql
  mysql:
    build: 
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=ip
    ports:
      - '3306:3306'