services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10s ; python ./script.py"
    environment:
      - FIND_IP_LOCATION=1.1.1.1
    depends_on:
      - mysql
  mysql:
    build: 
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    environment:
      # - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=ip
    secrets:
      - db_root_password
    ports:
      - '3306:3306'

secrets:
  db_root_password:
    file: my-secret-pw.txt